branch-defaults:
  default:
    environment: Default-Environment
  master:
    environment: Default-Environment
environment-defaults:
  Default-Environment:
    branch: null
    repository: null
global:
  application_name: My First Elastic Beanstalk Application
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.09 v2.3.0 running Go 1.5
  default_region: us-west-2
  profile: eb-cli
  sc: git
